### PR TITLE
Fix seeding errors that caused EF Core to crash. 

### PR DESCRIPTION
**Pull request by bchavez**
Regarding: https://github.com/bchavez/Bogus/issues/127.

Changes:
1. Added `EnsureDeleted()` on startup to destroy and re-create the database. `EnsureDeleted()` was used to avoid these precondition checks from bailing: `AddUsers() -> if (_context.AppIdentityUser.Any()) return;` and partially filling tables when debugging. Feel free to remove `EnsureDeleted()`.

2. There were some copy/paste errors, for example, `AddDepartments()`:
```
var fakeDepts =
    new Faker<CrmUnit>()
        .RuleFor(c => c.Name, f => f.PickRandom(depts))
        .RuleFor(c => c.Type, f => f.Company.CatchPhrase())
        .RuleFor(c => c.Type, "Department")
        .Generate(30);
```
where `c.Type` was defined twice on `Faker<CrmUnit>`. `c.Description` was always null on insert. The attributes for `CrmUnit` dictate 3 required fields: 
```
public class CrmUnit
{
    public string Id { get; set; }

    [Required]    ...
    public string Name { get; set; }

    [Required]    ...
    public string Type { get; set; }

    [Required]    ...
    public string Description { get; set; }
}
```
So, when EF does an INSERT, EF throws a `NullReferenceException`. The copy/paste error was also found in`AddCompanies()`.

3. Additionally, an out of array index out of bounds error was found in `AddDepartments()`:
```
foreach (var dept in fakeDepts)
{
    var random = new Random().Next(0, fakeDepts.Count);
    dept.Parent = fakeCompanies[random];
    dept.ParentId = dept.Parent.ParentId;
}
```
which should have been:
```
foreach (var dept in fakeDepts)
{
    var random = new Random().Next(0, fakeCompanies.Count);
    dept.Parent = fakeCompanies[random];
    dept.ParentId = dept.Parent.ParentId;
}
```

----

Please try these changes and let me know how it goes.

I think overall, the `NullReferenceException` was ultimately due to missing `[Required]` fields on INSERT with `EF.Core` and really nothing to do with **Bogus**. Still not entirely sure how the stack trace in your original issue failed, but I was able to successfully seed the database with these fixes to `Seeder.cs`.

Also, sorry for taking so long, got sidetracked a few times. :+1: 

-Brian

### CODE REVIEW

**Comment by feldrim** [comment]
Thank you for your great code review. Yet, the problem in adding CrmUsers remains:

```
var fakeUsers = new Faker<CrmUser>()
    .RuleFor(u => u.UserName, f => f.Person.UserName) //this is the line where NullException is thrown on variable f
    .RuleFor(u => u.Email, f => f.Person.Email)
    .RuleFor(u => u.EmailConfirmed, true)
    .Generate(30);

foreach (var user in fakeUsers)
{
    var result = _userManager.CreateAsync(user, $"{user.UserName}+000").Result;
    if (!result.Succeeded) AddErrors(result);
}
```

**Comment by bchavez** [comment]
Hi @feldrim ,

I'm still not able to reproduce the issue anymore:

chrome_1148

The web app seems to be seeding data and running fine on my box. :disappointed: 

I still have a feeling there must be some kind of external factor somewhere.

If you have any ideas how I can reproduce the issue, let me know.

Also, if you are willing to do Google Hangout, Skype, or Screen Share to get to the bottom of it, I'd be to join and help you debug the issue remotely. But as of this moment, I can't reproduce the issue anymore after submitting the changes in the PR.

-Brian

**Comment by feldrim** [comment]
It's really funny that I get the same error after a day. I've checked out to the commit before your PR and made changes step by step. Yet, I get the same null exception error on the same place. It's hilarious and pathetic at the same time.

**Comment by feldrim** [comment]
When I changed email and username to seed using `Name `instead of `Person`, it worked. It seems there's an issue with `Person` class.

**Comment by bchavez** [comment]
Yea, not really sure what to say. It's pretty frustrating.

I set two breakpoints, here: 
https://github.com/feldrim/Fiver.Security.AspIdentity/blob/e9e44bd005e40a85143423e525a2106b0cb58177/Security.AspIdentity/Program.cs#L45
and here:
https://github.com/feldrim/Fiver.Security.AspIdentity/blob/e9e44bd005e40a85143423e525a2106b0cb58177/Security.AspIdentity/Seeder.cs#L27

Basically stepped over `AddRoles()`, `AddUsers()`, etc, until the `try{}catch{}` breakpoint hit. Then I took note of the section that was throwing the exception. Re-ran, taking a closer look at the section that was failing and found those errors in the PR.

Also, just for reference, I have **.NET Core 2.0.3** installed.
```
R:\>dotnet --version
2.0.3
```
The only thing that might help is probably removing the `try{}catch{}` statement, so every run, the failure bottoms out near the error instead of bubbling up in the top `try/catch`. It might make debugging `Seeder` a little easier.

The null `Person` person object just doesn't make sense to me. One other thing is to verify that .NET is loading the most up to date **Bogus** version:

Breakpoint somewhere inside `Seeder`, run, and go to **Visual Studio Menu > Debug > Windows > Modules**:
devenv_1152

```
var version = typeof(Faker).Assembly.FullName; //works too
```

Yours should read `Version: 22.0.2.0`; if it's anything different then that could be a source of a problem.

If you put a failing unit test together, or another sample project for me that reproduces the problem, please feel free to reach out and let me know. I'd really like to help you solve this issue if it turns out to be a problem inside **Bogus**.

**Pull request merged**
